<div id="sejarah">
	<h1><center><strong>Sejarah KMB Dhamma&ntilde;ano ITB</strong></center></h1>
	<center><?php echo CHtml::image(Yii::app()->request->baseUrl."/images/Sejarah.jpg", "Sekre KMB", array(""));?></center>
	<p>Keluarga Mahasiswa Buddhis (KMB) Dhamma&ntilde;ano Institut Teknologi Bandung (ITB) dibentuk pada tahun 1991 atas prakarsa sejumlah mahasiswa Buddhis ITB yang merasakan perlu adanya wadah organisasi untuk menampung aspirasi dari mahasiswa-mahasiswi Buddhis di ITB.</p>
	<p>Di ITB pada tahun 60-an sudah ada unit kemahasiswaan yang berbentuk agama Buddha. Namun unit tersebut tidak bertahan lama. Lalu pada penghujung tahun 1989 para mahasiswa Buddhis mulai memikirkan dan mencoba merealisasikan KMB ITB dengan dimotori oleh dua orang mahasiswa Buddhis yaitu Budiman (IF 88) dan Gunardi (IF 87). Langkah pertama yang dilakukan adalah menghubungi Biro Administrasi ITB untuk mendapatkan informasi tentang mahasiswa ITB yang beragama Buddha. Kemudian mereka menghimpun mahasiswa Buddhis dari berbagai angkatan di ITB. Pada awal Oktober 1991, sekitar 20 orang mahasiswa bersepakat untuk membentuk suatu wadah yaitu KMB. Logo KMB kemudian mulai didesain dan namanya diminta dari Bhikkhu Nyanakusalo. Beliau memberikan nama "Dhamma&ntilde;ano" yang artinya "Pengetahuan Dharma".</p>
	<p>KMB Dhamma&ntilde;ano ITB mengadakan pertemuan setiap hari Jumat pk 11.00 di ruang 9023. Pada awalnya KMB Dhamma&ntilde;ano ITB tidak memiliki sekretariat di kampus ITB. Biasanya para anggota KMB Dhamma&ntilde;ano ITB berkumpul di Vihara Vimmala Dharma atau di rumah kost para anggota KMB. Pada tahun 1999 KMB ITB mendapatkan ruangan Sunken Court E-09 dari pihak ITB. Ruangan tersebut digunakan bersama oleh KMB, UBG, dan Sinar Putih. Lalu pada tahun 2004 ITB mengadakan relokasi unit. Ruang Sunken Court E-09 menjadi sekretariat KMB dan KMH. Setelah KMH mengajukan surat pernyataan bahwa mereka tidak lagi memakai ruangan tersebut maka Sunken Court E-09 menjadi sekretariat KMB Dhamma&ntilde;ano ITB. Akhirnya pada tanggal 4 Oktober 1991 terbentuk lah Keluarga Mahasiswa Buddhis Dhamma&ntilde;ano ITB yang saat ini berkedudukan di Sunken Court E-09.</p>
	<p>KMB ITB memiliki susunan kepengurusan organisasi yang terdiri atas BPH (Badan Pengurus Harian), Koordinator Divisi, serta kepanitiaan yang berada di bawah koordinasi BPH. Oh iya, tidak lupa juga ada dewan Penasehat. Kegiatan kepanitiaan yang rutin diadakan adalah Panitia Penerimaan Anggota Baru (PPAB) setahun sekali. Meditation Workshop setahun sekali juga. Dan Dharmabakti Desa Buddhis (DDB) setiap 2 tahun sekali. Selain itu divisi-divisi di KMB pun mempunyai program-program rutin yang diadakan untuk memfasilitasi minat, bakat dan aspirasi dari anggota KMB seperti misalnya Jumatan yang diadakan tiap seminggu sekali untuk mengisi waktu anggota KMB selama kawan-kawan yg muslim menjalankan shalat jumat. Juga ada program mentoring dari divisi kerohanian yang sasaran utamanya adalah anak-anak baru (angkatan termuda) tetapi tidak menutup kemungkinan bila ada angkatan atas yang ingin ikut serta. KMB ITB juga mempunyai program kakak asuh Kusaladhana yang diorganisir oleh Divisi Pengabdian Masyarakat (DPM), di mana KMB ITB mengangkat adik asuh dari desa-desa Buddhis yang dikunjungi pada saat DDB untuk dibiayai sekolahnya.</p>
	<p>Selain kegiatan-kegiatan yang sifatnya resmi dan serius tersebut, KMB juga memiliki acara-acara yang sifatnya fun misalnya olahraga bareng (sepak bola, basket, badminton, dll), kompetisi kartu (truf, capsa, dll), serta jumatan kesenian di mana setiap angkatan menunjukkan kemampuannya dalam berkarya di bidang seni. Jadi di KMB selain kita bisa belajar berorganisasi, kita juga dapat memperdalam pengetahuan dhamma kita dan juga bersenang-senang dengan teman-teman se-dhamma.</p>
	<p>So buat anak-anak KMB, mulai angkatan jadul sampe yg paling muda. Sering-sering ya mengunjungi website ini dan jangan lupa sering-sering main ke sunken ya buat yang masih di kampus.</p>
</div>